### ISSUE TITLE
clash with .left and .right

### ISSUE THREAD

**Issue by pacharya** [typelevel/scalaz-scalatest#24]
When I just add this import, never mind use this, I get -

```
[error] /Users/pacharya/Documents/workspace/mola/src/test/scala/com/versal/mola/TestBase.scala:29: value right is not a member of com.typesafe.config.Config
[error]             case Success(configObj) => configObj.right
```

So I change that to `\/.right(configObj)`. It compiles

Now actual test run has this issue -

```
[error] Uncaught exception when running com.versal.mola.entity.RabbitConnectionTest: java.lang.NoSuchMethodError: scalaz.syntax.Syntaxes$id$.ToIdOps(Ljava/lang/Object;)Lscalaz/syntax/IdOps;
sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: scalaz.syntax.Syntaxes$id$.ToIdOps(Ljava/lang/Object;)Lscalaz/syntax/IdOps;
	at com.versal.mola.config.ConfigParser$class.getT(ConfigParser.scala:24)
	at com.versal.mola.settings.ConnectionSettings$.getT(ConnectionSettings.scala:71)
	at com.versal.mola.config.ConfigParser$$anonfun$22.apply(ConfigParser.scala:82)
	at com.versal.mola.config.ConfigParser$$anonfun$22.apply(ConfigParser.scala:82)
	at com.versal.mola.settings.ConnectionSettings$.fromConfig(ConnectionSettings.scala:172)
	at com.versal.mola.TestBase$$anonfun$buildSettingsObjects$1.apply(TestBase.scala:39)
	at com.versal.mola.TestBase$$anonfun$buildSettingsObjects$1.apply(TestBase.scala:38)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at com.versal.mola.TestBase$class.buildSettingsObjects(TestBase.scala:38)
	at com.versal.mola.entity.RabbitConnectionTest.buildSettingsObjects(RabbitConnectionTest.scala:20)
	at com.versal.mola.entity.RabbitConnectionTest$$anonfun$4.apply(RabbitConnectionTest.scala:27)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
	at com.versal.mola.entity.RabbitConnectionTest.org$scalatest$BeforeAndAfterAll$$super$run(RabbitConnectionTest.scala:20)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
	at com.versal.mola.entity.RabbitConnectionTest.run(RabbitConnectionTest.scala:20)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

There seems to be a clash between the implicits imported in `scalaz.syntax.id._` that enable us to lift values into the right and left side of the disjunction with `.right` and `.left` respectively, and this package.

My dependency -

```
  // scalaz
  , "org.scalaz"                         %% "scalaz-core"          % "7.0.6"
...
  // test
  , "org.scalatest"                      %% "scalatest"            % "3.0.1" % "test"
  , "org.typelevel"                      %% "scalaz-scalatest"     % "1.1.2" % "test"
```

**Comment by coltfred** [comment]
I believe the problem here is that you're using scalaz-core 7.0.6, but the scalaz-scalatest version you're using relies on scalaz 7.2.x.

You can see the supported versions matrix [here](https://github.com/typelevel/scalaz-scalatest#setup).

**Comment by pacharya** [comment]
Thank you
